### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by jaxxstorm** [tellerhq/beta-issues#10] opened 2017-06-22 05:52 UTC
I played around with teller, and I now don't feel comfortable with my bank being connected.

Is there a way I can remove the connection, or delete my account?

**Comment by stevegraham** [comment] 2017-06-23 14:30
As confirmed via email your enrollment has been deleted. Leaving this issue open until a self-serve delete enrollment feature has shipped.

**Comment by stevegraham** [comment] 2017-06-23 23:51
Closing as dupe of #7

**Closed as completed by stevegraham** 2017-06-23 23:51 UTC
