### ISSUE TITLE
Better account recovery process?

### ISSUE THREAD

**Issue by petems** [tellerhq/beta-issues#21] opened 2017-08-02 10:57 UTC
My 1Password failed to save my account details properly, so I asked for a password reset early July. Havent had a response since I showed my Keybase.io account

https://twitter.com/PeterSouter/status/881854759984128000
![screenshot_20170802-115348](https://user-images.githubusercontent.com/1064715/28870831-a5f5ff30-7779-11e7-8dad-aebf65c3ec42.png)

Is there another way to ask for password reset?

**Comment by stevegraham** [comment] 2017-08-02 11:12
Duplicate of #19. Will close this as duplicate once your password has been reset. Please check your Keybase 🙂

**Closed as completed** 2017-08-02 17:01 UTC
